name: CI-CD

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: timbucket0812
  RESOURCE_PATH: ./src/main/resources/application.yml
  CODE_DEPLOY_APPLICATION_NAME: tim-code-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: tim-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Set yaml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application-prod.yml
        env:
          override.value: 'from deploy.yml'
          jwt.secret: ${{ secrets.JWT_SECRET_KEY }}
          spring.datasource.username: ${{ secrets.AWS_RDS_USERNAME }}
          spring.datasource.password: ${{ secrets.AWS_RDS_PASSWORD }}
          spring.redis.host: ${{ secrets.REDIS_HOST }}
          spring.redis.port: ${{ secrets.REDIS_PORT }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

        # [2]
      - name: Build with Gradle
        run: ./gradlew build

        # [3]
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .

        # [4]
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

        # [5]
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://timbucket0812/$GITHUB_SHA.zip

        # [6]
      - name: Code Deploy
        run: | 
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=timbucket0812,bundleType=zip,key=$GITHUB_SHA.zip
